/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/VJTnm8H8DkX
 */
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";

export function UploadImages() {
  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-base">Upload Images</CardTitle>
        <CardDescription>
          Drop your images here or click to browse.
        </CardDescription>
      </CardHeader>
      <CardContent className="flex items-center justify-center p-6">
        <div className="w-full border-dashed border-2 border-gray-200 border-[#d9d9d9] rounded-lg p-6 flex items-center justify-center">
          <UploadIcon className="w-12 h-12 text-gray-300" />
          <span className="text-sm text-gray-500">
            Drag and drop your files here
          </span>
        </div>
      </CardContent>
      <CardFooter>
        <Button size="sm" variant="ghost">
          Add more
        </Button>
        <Button className="ml-auto" size="sm" variant="ghost">
          Clear all
        </Button>
      </CardFooter>
    </Card>
  );
}

function UploadIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 1-2 2H5a2 1-2-2v-4" />
      <polyline points="17 8 12 3 7" />
      <line x1="12" x2="12" y1="3" y2="15" />
    </svg>
  );
}
