/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/SVjTBGcByIR
 */

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import Link from "next/link";
import Image from "next/image";

import Header from "@/components/header";
export default function LandingPage() {
  return (
    <div key="1" className="flex flex-col min-h-screen">
      <div className="flex flex-col">
        <Header />
        <main className="flex-1 bg-white">
          <section
            className="flex items-center justify-center h-screen text-center"
            style={{
              backgroundImage: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url(/pakistan.png)`,
              backgroundSize: "cover",
              backgroundPosition: "center",
              backgroundRepeat: "no-repeat",
            }}
          >
            <div className="mb-24">
              <div className="h-screen flex items-center justify-center animate-fadeIn">
                <h1 className="text-8xl font-bold text-white">
                  <span
                    className="text-white fancy-font"
                    style={{ color: "#67e8f9" }}
                  >
                    Flood Finder
                  </span>
                </h1>
              </div>
            </div>
          </section>
          <div className="flex flex-row items-center justify-center text-center mt-28 mb-24">
            <Image
              src="/foodedhouse1.png"
              alt="Flooded House 1"
              width={400}
              height={300}
              className="rounded-lg"
            />
            <div className="flex flex-col items-center justify-center text-center mx-10">
              <h2 className="text-4xl text-gray-700">In 2022,</h2>
              <h1 className="text-8xl text-gray-700 py-8">8 million</h1>
              <h2 className="text-2xl text-gray-700">
                homes were destroyed from floods in Pakistan.
              </h2>
              <h2 className="text-2xl text-gray-700 py-8">
                Many were only observable via ariel footage.
              </h2>
            </div>
            <Image
              src="/foodedhouse2.png"
              alt="Flooded House 2"
              width={400}
              height={300}
              className="rounded-lg"
            />
          </div>

          <h1 className="flex text-center justify-center text-4xl text-gray-700 py-8 mx-10">
            We let first responsers respond quick by using Flood Finder.
          </h1>

          <div className="flex flex-row items-center justify-center text-center mt-28 mb-24">
            <Image
              src="/badflooding.png"
              alt="Severely Flooded Village"
              width={400}
              height={300}
              className="rounded-lg"
            />
            <div className="flex flex-col items-center justify-center text-center mx-3">
              <h2 className="text-4xl text-gray-700">
                Train a Custom AI Model
              </h2>
              <h1 className="text-8xl text-gray-700 py-8">Identify</h1>
              <h2 className="text-2xl text-gray-700">
                Severely flooded villages vs relatively unaffected villages.
              </h2>
              <h2 className="text-2xl text-gray-700 py-8">
                Know which areas to respond to first.
              </h2>
            </div>
            <Image
              src="/unaffected.png"
              alt="Unaffected Village"
              width={400}
              height={300}
              className="rounded-lg"
            />
          </div>

          <div className="flex justify-center py-8">
            <Link href="/train">
              <a className="text-4xl text-gray-700 underline">Train Model</a>
            </Link>
          </div>
        </main>
        <footer className="flex items-center justify-center h-16 bg-blue-200">
          <p className="text-gray-600 dark:text-gray-400">
            ©Flood Finder. All rights reserved.
          </p>
        </footer>
      </div>
    </div>
  );
}
