/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/SVjTBGcByIR
 */

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import Link from "next/link";
import Image from "next/image";

import Header from "@/components/header";
export default function LandingPage() {
  return (
    <div key="1" className="flex flex-col min-h-screen">
      <div className="flex flex-col">
        <Header />
        <main className="flex-1 bg-white">
          <section
            className="flex items-center justify-center h-screen text-center"
            style={{
              backgroundImage: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url(/pakistan.png)`,
              backgroundSize: "cover",
              backgroundPosition: "center",
              backgroundRepeat: "no-repeat",
            }}
          >
            <div className="mb-24">
              <div className="h-screen flex items-center justify-center animate-fadeIn">
                <h1 className="text-8xl font-bold text-white">
                  <span
                    className="text-white fancy-font"
                    style={{ color: "#67e8f9" }}
                  >
                    Flood Finder
                  </span>
                </h1>
              </div>
            </div>
          </section>
          <div className="flex flex-row items-center justify-center text-center mt-28 mb-24">
            <Image
              src="/foodedhouse1.png"
              alt="Flooded House 1"
              width={400}
              height={300}
              className="rounded-lg"
            />
            <div className="flex flex-col items-center justify-center text-center mx-10">
              <h2 className="text-4xl text-gray-700">In 2022,</h2>
              <h1 className="text-8xl text-gray-700 py-8">8 million</h1>
              <h2 className="text-2xl text-gray-700">
                homes were destroyed from floods in Pakistan.
              </h2>
              <h2 className="text-2xl text-gray-700 py-8">
                Many were only observable via ariel footage.
              </h2>
            </div>
            <Image
              src="/foodedhouse2.png"
              alt="Flooded House 2"
              width={400}
              height={300}
              className="rounded-lg"
            />
          </div>

          <h1 className="flex text-center justify-center text-4xl text-gray-700 py-8 mx-10">
            We let first responsers respond quick by using Flood Finder.
          </h1>

          <div className="flex flex-row items-center justify-center text-center mt-28 mb-24">
            <Image
              src="/badflooding.png"
              alt="Severely Flooded Village"
              width={400}
              height={300}
              className="rounded-lg"
            />
            <div className="flex flex-col items-center justify-center text-center mx-3">
              <h2 className="text-4xl text-gray-700">
                Train a Custom AI Model
              </h2>
              <h1 className="text-8xl text-gray-700 py-8">Identify</h1>
              <h2 className="text-2xl text-gray-700">
                Severely flooded villages vs relatively unaffected villages.
              </h2>
              <h2 className="text-2xl text-gray-700 py-8">
                Know which areas to respond to first.
              </h2>
            </div>
            <Image
              src="/unaffected.png"
              alt="Unaffected Village"
              width={400}
              height={300}
              className="rounded-lg"
            />
          </div>

          <div className="flex justify-center py-8">
            <Link href="/train">
              <a className="text-4xl text-gray-700 underline">Train Model</a>
            </Link>
          </div>
        </main>
        <footer className="flex items-center justify-center h-16 bg-blue-200">
          <p className="text-gray-600 dark:text-gray-400">
            ©Flood Finder. All rights reserved.
          </p>
        </footer>
      </div>
    </div>
  );
}
function MailIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  );
}

function HeartHandshakeIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z" />
      <path d="M12 5 9.04 7.96a2.17 2.17 0 0 0 0 3.08v0c.82.82 2.13.85 3 .07l2.07-1.9a2.82 2.82 0 0 1 3.79 0l2.96 2.66" />
      <path d="m18 15-2-2" />
      <path d="m15 18-2-2" />
    </svg>
  );
}

function FacebookIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  );
}

function FigmaIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 5.5A3.5 3.5 0 0 1 8.5 2H12v7H8.5A3.5 3.5 0 0 1 5 5.5z" />
      <path d="M12 2h3.5a3.5 3.5 0 1 1 0 7H12V2z" />
      <path d="M12 12.5a3.5 3.5 0 1 1 7 0 3.5 3.5 0 1 1-7 0z" />
      <path d="M5 19.5A3.5 3.5 0 0 1 8.5 16H12v3.5a3.5 3.5 0 1 1-7 0z" />
      <path d="M5 12.5A3.5 3.5 0 0 1 8.5 9H12v7H8.5A3.5 3.5 0 0 1 5 12.5z" />
    </svg>
  );
}
